config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'summaries#index'

  resources :summaries do
    resources :links, except: [:index, :show]
  end

  resources :sidebars, only: [:edit]

  resources :pages, only: [:show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :summary
  validates_presence_of :url, :text
end

app/models/page.rb
class Page < ApplicationRecord
  validates_presence_of :title
  validates_presence_of :body
end

app/models/summary.rb
class Summary < ApplicationRecord
  has_many :links, dependent: :destroy
  validates_presence_of :heading, :body
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
def new
  @link = Link.new
end

def edit
  @link = Link.find(params[:id])
end

def update
  @link = Link.find(params[:id])
  if @link.update(edit_link_params)
    redirect_to root_path
  else
    render :edit
  end
end

def create
  # @summary = Summary.find(params[:id])
  @link = Link.new(new_link_params)
  @link.summary_id = params[:summary_id]
  if @link.save
    redirect_to root_path
  else
    render :new
  end
end

def destroy
  @link = Link.find(params[:id])
  @link.destroy
  redirect_to root_path
end


private
  def new_link_params
    params.require(:links).permit(:text, :url)
  end

  def edit_link_params
    params.require(:link).permit(:text, :url)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    @page = Page.find(params[:id])
  end

  def edit
    @page = Page.find(params[:id])
  end

  def update
    @page = Page.find(params[:id])
    if @page.update(edit_page_params)
        redirect_to page_path(@page.id)
    else
      render :edit
    end
  end

  private
  def edit_page_params
    params.require(:page).permit(:title, :body, :sidebar)
  end

end

app/controllers/sidebars_controller.rb
class SidebarsController < ApplicationController
  def edit
    @page = Page.find(params[:id])
  end
end

app/controllers/summaries_controller.rb
class SummariesController < ApplicationController
  def index
    @summaries = Summary.all
  end

  def new
    @summary = Summary.new
  end

  def edit
    @summary = Summary.find(params[:id])
  end

  def update
    @summary = Summary.find(params[:id])
    if @summary.update(edit_summary_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def create
    @summary = Summary.create(new_summary_params.except(:url_one, :text_one, :url_two, :text_two, :url_three, :text_three))
    if @summary.valid?
      @summary = Summary.last
      if params[:summaries][:url_one]
        @link = Link.new({url: params[:summaries][:url_one], text: params[:summaries][:text_one]})
        @link.summary_id = @summary.id
        @link.save
      end
      if params[:summaries][:url_two]
        @link = Link.new({url: params[:summaries][:url_two], text: params[:summaries][:text_two]})
        @link.summary_id = @summary.id
        @link.save
      end
      if params[:summaries][:url_three]
        @link = Link.new({url: params[:summaries][:url_three], text: params[:summaries][:text_three]})
        @link.summary_id = @summary.id
        @link.save
      end
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    @summary = Summary.find(params[:id])
    @summary.destroy
    redirect_to root_path
  end

  private
  def new_summary_params
    params.require(:summaries).permit(:heading, :subheading, :body, :image_url, :url_one, :text_one, :url_two, :text_two, :url_three, :text_three)
  end

  def edit_summary_params
    params.require(:summary).permit(:heading, :subheading, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Desc</title>
    <meta name="viewport" content="width=device-width" />
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'foundation.css', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'foundation.min.js', 'data-turbolinks-track': 'reload' %>

  </head>
  <body>

    <!-- <a href="/"><img class="cornerlogo" src="/assets/keylogo.png" alt=""></a>
    <a href="/"><img class="cornerlogo-mobile" src="/assets/key3desc.png" alt=""></a> -->

    <div class="page-wrap">

  <div class="title-bar" data-responsive-toggle="example-menu" data-hide-for="medium">
          <%= link_to( image_tag("key3desc", class: "cornerlogo-mobile"), root_path) %>
  <button class="menu-icon" type="button" data-toggle="example-menu"></button>
</div>

<div class="top-bar" id="example-menu">
      <%= link_to( image_tag("keylogo", class: "cornerlogo"), root_path) %>

  <div class="top-bar-left">
    <ul  class="dropdown vertical medium-horizontal menu" data-dropdown-menu>

      <!-- <li class="menu-text">SITE TITLE</li> -->
      <li>
        <a href="/pages/2">What We Do</a>
        <ul class="menu submenu vertical">
          <li><a href="/pages/10">Emergency Shelter</a></li>
          <li><a href="/pages/11">Health Services</a></li>
          <li><a href="/pages/12">Permanent Supportive Housing</a></li>
          <li><a href="/pages/13">Employment Services</a></li>
          <li><a href="/pages/14">Crisis Response</a></li>
          <li><a href="/pages/15">Innovation</a></li>
          <li><a href="/pages/16">Housing First</a></li>
          <li><a href="/pages/17">Vulnerability Assessment Tool</a></li>
          <li><a href="/pages/18">Research</a></li>
          <li><a href="/pages/6">Consultation and Technical Assistance</a></li>
        </ul>
      </li>
      <li><a href="/pages/1">About Us</a></li>
      <li><a href="/pages/7">Learn More</a></li>
      <li><a href="/pages/8">Get Involved</a></li>
      <li><a href="/pages/9">Contact Us</a></li>
      <li class="donate" id="donate"><a href="https://donatenow.networkforgood.org/DESC">Donate</a></li>
    </ul>
      </div>
<div class="login">
      <ul  class="">
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong>.
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
        <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %> |
        <%= link_to "New User", new_user_registration_path, :class => 'navbar-link'  %>
      <% end %>
    </ul>
</div>


</div>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

    <%= yield %>
  </div>
      <div class="footer">
        <p class="footer-text">
Contact Us | Privacy Policy (HIPAA) | Site Map | DESC © 2010 | 515 Third Avenue, Seattle. WA 98104 | 206-464-1570</p>
      </div>
  </body>
</html>

app/views/links/edit.html.erb
<div class="errors">
  <ul class="errors">
    <% if @link %>
      <% @link.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    <% end %>
  </ul>
</div>

<div class="row">
  <div class="new-summary medium-6 columns">
    <%= form_for @link, url: summary_link_path do |f| %>
      <div>
        <%= f.label :text %>
        <%= f.text_field :text, value: @link.text %>
      </div>
      <div>
        <%= f.label :url %>
        <%= f.text_field :url, value: @link.url %>
      </div>
      <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/links/new.html.erb
<div class="errors">
  <ul class="errors">
    <% if @link %>
      <% @link.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    <% end %>
  </ul>
</div>

<div class="row">
  <div class="new-summary medium-6 columns">
    <%= form_for :links, url: summary_links_path do |f| %>
      <div>
        <%= f.label :text %>
        <%= f.text_field :text %>
      </div>
      <div>
        <%= f.label :url %>
        <%= f.text_field :url %>
      </div>
      <%= f.submit :'save link' %>
    <% end %>
  </div>
</div>

app/views/pages/edit.html.erb
<div class="">
    <%= form_for @page, url: page_path do |f| %>
  <div class="">
    <ul class="errors">
      <% if @page %>
        <% @page.errors.full_messages.each do |error| %>
          <li><%= error %></li>
        <% end %>
      <% end %>
    </ul>
  </div>
  <div class="">
    <%= f.label :title %>
    <%= f.text_field :title, value: @page.title %>
  </div>
  <div class="">
    <%= f.label :body %>
    <%= f.text_area :body, value: @page.body, class: "tinymce" %>
  </div>
    <%= f.submit "Submit" %>
    <% end %>
</div>

<%= tinymce %>

app/views/pages/show.html.erb
<div class="container">
  <div class="row summary">
    <div class="medium-8 columns">
        <% if user_signed_in? %>
          <%= link_to "Edit", edit_page_path %>
        <% end %>
        <p><%= raw(@page.body) %></p>
    </div>
    <div class="medium-4 columns sidebar">
      <% if user_signed_in? %>
        <%= link_to "Edit", edit_sidebar_path %>
      <% end %>
      <% if @page.sidebar %>
        <p><%= raw(@page.sidebar) %></p>
      <% end %>
    </div>
  </div>
</div>

app/views/sidebars/edit.html.erb
<div class="">
    <%= form_for @page, url: page_path do |f| %>
  <div class="">
    <ul class="errors">
      <% if @page %>
        <% @page.errors.full_messages.each do |error| %>
          <li><%= error %></li>
        <% end %>
      <% end %>
    </ul>
  </div>
  <div class="">
    <%= f.label :sidebar %>
    <%= f.text_area :sidebar, value: @page.sidebar %>
  </div>
    <%= f.submit "Submit" %>
    <% end %>
</div>

<%= tinymce %>

app/views/summaries/_carousel.html.erb
<!-- <div class="image-slides">
  <img class="carousel" src="/assets/Jerome1.jpg">
  <img class="carousel" src="/assets/whatwedoNoahimage.jpg">
  <img class="carousel" src="/assets/AnnualReport.jpg">
</div> -->

app/views/summaries/_image.html.erb
<div class="medium-5 columns">
  <img class="landing-image" src="<%= summary.image_url %>" alt="#{<%= summary.heading %>} image">
</div>

app/views/summaries/_learn_more_links.html.erb
<div class=" medium-5 large-3 columns">
  <div class="learn-more">
    <a href="#">
      <div class="learn-more-heading white">
        <h4>Learn More</h4>
      </div></a>
      <% if user_signed_in? %>
      <%= link_to "New", new_summary_link_path(summary.id), class: "summary", method: "get" %>
      <% end %>

      <% summary.links.each do |link| %>
      <p>
        <% if user_signed_in? %>
        <%= link_to "✎", edit_summary_link_path(summary.id, link.id), class: "summary", method: "get" %>
        <%= link_to "x", summary_link_path(summary.id, link.id), method: "delete", class: "summary" ,data: {confirm: "Are you sure? (this action can not be undone)"} %>
        <% end %>
        <a href="<%= link.url %>"><%= link.text %></a></p>
        <% end %>
      </div>
    </div>

app/views/summaries/_text_and_links.html.erb
<div class="medium-7 columns">
  <% if user_signed_in? %>
    <%= link_to "✎", edit_summary_path(summary.id), class: "summary", method: "get" %>
    <%= link_to "x", summary_path(summary.id), method: "delete", class: "summary" ,data: {confirm: "Are you sure? (this action can not be undone)"} %>
  <% end %>
  <div class="topic-heading">
    <h1><a href="#"><%= summary.heading.capitalize %></a></h1>
    <h3 class="subheading"><%= summary.subheading.capitalize %></h3>
  </div>

  <div class="desktop-links">
    <%= render partial: "learn_more_links", locals: {summary: summary} %>
  </div>

  <div class="topic-summary medium-7 large-9 columns">
    <h5><%= summary.body %></h5>
  </div>

  <div class="mobile-links">
    <%= render partial: "learn_more_links", locals: {summary: summary} %>
  </div>
</div>

app/views/summaries/edit.html.erb
<div class="errors">
  <ul class="errors">
    <% if @summary %>
      <% @summary.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    <% end %>
  </ul>
</div>

<div class="row">
  <div class="new-summary medium-6 columns">
    <%= form_for @summary, url: summary_path do |f| %>
      <div>
        <p>
          <%= f.label :heading %>
          <%= f.text_field :heading,  size: "35", value: @summary.heading %>
        </p>
      </div>
      <div>
        <%= f.label :subheading %>
        <%= f.text_field :subheading, value: @summary.subheading %>
      </div>
      <div>
        <%= f.label :body %>
        <%= f.text_field :body, value: @summary.body %>
      </div>
      <div>
        <%= f.label :image_url %>
        <%= f.text_field :image_url, value: @summary.image_url %>
      </div>
      <%= f.submit :Update %>
    <% end %>
  </div>
</div>

app/views/summaries/index.html.erb
  <div class="top-quote-box quote">
    <div class="row">
    <h2>Serving 3,500 homeless and formerly homeless men and women every day</h2>
      <div class="medium-8 columns"></div>
        <div class="donate-button medium-2 columns">
          <a href="https://donatenow.networkforgood.org/DESC" target="_blank">Donate Now</a>
        </div>
      </div>
    </div>

  <div class="container">
    <% if user_signed_in? %>
      <a href="/summaries/new"><div class="new-summary-link">New Summary</div></a>
    <% end %>

  <% @summaries.each_with_index do |summary, i| %>
  <div class="summary">
  <% if i%2 == 0 %> <!-- left aling even indexes -->
    <div class="row">
        <%= render partial: 'text_and_links', locals: {summary: summary} %>

        <%= render partial: 'image', locals: {summary: summary} %>
    </div>
   <% else %> <!-- right align odd indexes -->
    <div class="row">
      <div class="right-align">
        <div class="desktop-image">
          <%= render partial: 'image', locals: {summary: summary} %>
        </div>
      </div>
        <%= render partial: 'text_and_links', locals: {summary: summary} %>
        <div class="mobile-image">
          <%= render partial: 'image', locals: {summary: summary} %>
        </div>
    <% end %>
</div>

  <div class="mobile-spacing"></div>

  <% end %>
  </div>
</div>

app/views/summaries/new.html.erb
<div class="errors">
  <ul class="errors">
    <% if @summary %>
      <% @summary.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    <% end %>
  </ul>
</div>

<div class="row">
  <div class="new-summary medium-6 columns">
    <%= form_for :summaries, url: summaries_path do |f| %>
      <div>
        <p>
          <%= f.label :heading %>
          <%= f.text_field :heading,  size: "three5"%>
        </p>
      </div>
      <div>
        <%= f.label :subheading %>
        <%= f.text_field :subheading %>
      </div>
      <div>
        <%= f.label :body %>
        <%= f.text_field :body %>
      </div>
      <div>
        <%= f.label :image_url %>
        <%= f.text_field :image_url %>
      </div>
      <div class=:"link-field">
        <%= f.label :link_one_text %>
        <%= f.text_field :text_one %>

        <%= f.label :link_one_url %>
        <%= f.text_field :url_one %>
      </div>
      <div>
        <%= f.label :link_two_text %>
        <%= f.text_field :text_two %>
      </div>
      <div>
        <%= f.label :link_two_url %>
        <%= f.text_field :url_two %>
      </div>
      <div>
        <%= f.label :link_three_text %>
        <%= f.text_field :text_three %>
      </div>
      <div>
        <%= f.label :link_three_url %>
        <%= f.text_field :url_three %>
      </div>
      <%= f.submit :'save summary' %>
    <% end %>
  </div>
</div>